// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPysZv6bRPe5HBIAS5LLRM-pk_mhlv1Lo',
    appId: '1:145409309228:web:72b1d315aff4c7df8b6f89',
    messagingSenderId: '145409309228',
    projectId: 'tync-app',
    authDomain: 'tync-app.firebaseapp.com',
    storageBucket: 'tync-app.firebasestorage.app',
    measurementId: 'G-YSKHYDWZYM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmuQedlKC_H3iekdmvnWRE8uXJ4K1DomA',
    appId: '1:145409309228:android:e8237fd15672f2528b6f89',
    messagingSenderId: '145409309228',
    projectId: 'tync-app',
    storageBucket: 'tync-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDltQZkCs_bLx8oc0p4lQM0mlPM-HB9J2g',
    appId: '1:145409309228:ios:815ccdc5d746897a8b6f89',
    messagingSenderId: '145409309228',
    projectId: 'tync-app',
    storageBucket: 'tync-app.firebasestorage.app',
    iosBundleId: 'com.example.tync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDltQZkCs_bLx8oc0p4lQM0mlPM-HB9J2g',
    appId: '1:145409309228:ios:815ccdc5d746897a8b6f89',
    messagingSenderId: '145409309228',
    projectId: 'tync-app',
    storageBucket: 'tync-app.firebasestorage.app',
    iosBundleId: 'com.example.tync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPysZv6bRPe5HBIAS5LLRM-pk_mhlv1Lo',
    appId: '1:145409309228:web:2375994985d02a818b6f89',
    messagingSenderId: '145409309228',
    projectId: 'tync-app',
    authDomain: 'tync-app.firebaseapp.com',
    storageBucket: 'tync-app.firebasestorage.app',
    measurementId: 'G-HDJC0VCEQX',
  );
}
